In [26]:
import pandas as pd
import numpy as np

In [27]:
data_dir = "./data/demo_r_pjangroup.tsv"

In [69]:
data = pd.DataFrame.from_csv(data_dir, sep='\t')
data

,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
"unit,sex,age,geo\time",,,,,,,,,,,,,,,,,,,,,
"NR,F,TOTAL,AL",1431715,1423050,1417141,1424597,1430827,1437193,1444234,1451691,1459025,1468935,...,:,:,:,:,:,:,:,:,:,:
"NR,F,TOTAL,AL0",1431715,1423050,1417141,1424597,1430827,1437193,1444234,1451691,1459025,1468935,...,:,:,:,:,:,:,:,:,:,:
"NR,F,TOTAL,AL01",405598,405835,416845,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
"NR,F,TOTAL,AL02",585530,574010,552949,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
"NR,F,TOTAL,AL03",440587,443205,454906,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
"NR,F,TOTAL,ALXX",0,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
"NR,F,TOTAL,AT",4483749,4460424,4427918,4384529,4352447,4328238,4309977,4296293,4285442,4278068,...,4126432,4122811,4120947,4116117,4112289,4107857,4089274,4052348,4014682,3989903
"NR,F,TOTAL,AT1",1964998,1952123,1934748,1909925,1891217,1876351,1863066,1854135,1845858,1839514,...,1745752,1745041,1746195,1745115,1745427,1747041,1739459,1725294,1710008,1700829
"NR,F,TOTAL,AT11",149016,148416,148052,147246,146980,146694,146224,145579,145017,144528,...,141744,142008,142232,142371,142264,141890,141706,141157,140071,139775
"NR,F,TOTAL,AT12",847971,845249,839555,832975,828087,824527,823091,821187,819527,818188,...,784028,782265,780826,780046,778244,775697,772563,765016,758595,752424
"NR,F,TOTAL,AT13",968011,958458,947141,929704,916150,905130,893751,887369,881314,876798,...,819980,820768,823137,822698,824919,829454,825190,819121,811342,808630
"NR,F,TOTAL,AT2",915571,914535,911819,907636,905201,903847,903834,903867,904071,905108,...,899618,900191,900704,901583,901475,901119,900286,894671,890277,889103
"NR,F,TOTAL,AT21",287410,287516,287033,286371,285797,285872,286351,286798,287422,288294,...,290118,290065,290184,290320,289540,288999,288272,285421,283082,281917
"NR,F,TOTAL,AT22",628161,627019,624786,621265,619404,617975,617483,617069,616649,616814,...,609500,610126,610520,611263,611935,612120,612014,609250,607195,607186
"NR,F,TOTAL,AT3",1603180,1593766,1581351,1566968,1556029,1548040,1543077,1538291,1535513,1533446,...,1481062,1477579,1474048,1469419,1465387,1459697,1449529,1432383,1414397,1399971
"NR,F,TOTAL,AT31",742757,738861,733791,727840,722883,720064,718572,717375,717201,716999,...,700129,699175,698765,698241,697721,695867,691529,683873,675668,670153
"NR,F,TOTAL,AT32",282253,280536,278648,276378,274675,273680,272648,271855,271178,271165,...,264392,264264,263463,262300,261408,260321,258024,253624,250219,246020
"NR,F,TOTAL,AT33",380734,378448,375090,370936,368128,365217,363430,361611,360160,358975,...,340916,339256,337684,335443,333603,331687,328948,325329,321350,318816
"NR,F,TOTAL,AT34",197436,195921,193822,191814,190343,189079,188427,187450,186974,186307,...,175625,174884,174136,173435,172655,171822,171028,169557,167160,164982
"NR,F,TOTAL,BE",5784371,5762455,5741853,5713206,5687048 b,5665118,5635601 b,5598920 b,5527684,5484429,...,5220034,5209592,5198446,5184262,5175903,5160407,5144847,5122765,5106290,5087683
"NR,F,TOTAL,BE1",614177,611616,611496,605416,600073 b,596155,589404 b,582295 b,562751,552282,...,499503,499494,499006,497984,500008,499724,501042,502540,507530,510558
"NR,F,TOTAL,BE10",614177,611616,611496,605416,600073 b,596155,589404 b,582295 b,562751,552282,...,499503,499494,499006,497984,500008,499724,501042,502540,507530,510558
"NR,F,TOTAL,BE2",3313318,3297353,3280662,3264030,3248700 b,3235108,3220347 b,3200462 b,3166649,3144708,...,3003287,2995742,2988109,2978229,2969483,2958990,2947602,2932631,2919226,2905220
"NR,F,TOTAL,BE21",931849,926733,921759,916658,911543 b,907233,901723 b,894659 b,881873,874832,...,832039,830576,829098,826878,825260,823010,820451,816398,813481,810015
"NR,F,TOTAL,BE22",437528,435961,434332,432143,430222 b,428628,426757 b,424405 b,420639,417746,...,393517,391644,389439,386935,384824,382394,379608,376465,373652,370933
"NR,F,TOTAL,BE23",762422,758643,754237,749908,746241 b,742282,739346 b,734817 b,726956,720858,...,690798,689699,688276,686498,684753,683498,682243,680124,678164,676231
"NR,F,TOTAL,BE24",580092,576386,572406,568478,565326 b,562428,558953 b,554984 b,549209,545264,...,515559,513564,511583,508852,506593,503081,499765,496517,493318,489422
"NR,F,TOTAL,BE25",601427,599630,597928,596843,595368 b,594537,593568 b,591597 b,587972,586008,...,571374,570259,569713,569066,568053,567007,565535,563127,560611,558619
"NR,F,TOTAL,BE3",1856876,1853486,1849695,1843760,1838275 b,1833855,1825850 b,1816163 b,1798284,1787439,...,1717244,1714356,1711331,1708049,1706412,1701693,1696203,1687594,1679534,1671905
"NR,F,TOTAL,BE31",206773,205762,204723,203060,201753 b,200447,199137 b,197443 b,195407,193468,...,178179,176693,175098,173781,172382,170534,168615,166476,164273,161155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"NR,T,Y_LT5,UKH3",110232,110700,110463,109492,108447,107608,106296,104782,103201,101297,...,98200,98500,99100,100500,101800,102200,102500,102400,:,:
"NR,T,Y_LT5,UKI",623520,629090,633567,630682,625019,616595,602996,590239,579203,563137,...,492300,494200,494500,495100,494000,491100,488500,483500,:,:
"NR,T,Y_LT5,UKI3",69254,70569,71849,72309,72107,71230,69770,68524,67397,65743,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKI4",167338,168491,169635,168558,166763,163966,159848,157711,156994,154376,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKI5",145484,145783,145739,144057,142250,140371,137899,135027,131647,126926,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKI6",91041,91460,92201,91969,91329,90390,88554,86078,83662,81117,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKI7",150403,152787,154143,153789,152570,150638,146925,142899,139503,134975,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKJ",532257,537775,544459,547389,547980,546629,540873,530623,517892,505352,...,485200,487600,490800,495000,498200,498900,500600,500100,:,:
"NR,T,Y_LT5,UKJ1",151773,153716,156375,157704,158298,158283,156785,153496,149185,144909,...,135000,136000,136800,138000,138400,137900,138000,137100,:,:
"NR,T,Y_LT5,UKJ2",159867,161428,163634,164617,164921,164538,162659,159692,156189,152755,...,147800,147300,147200,147400,147600,147200,147800,147500,:,:
"NR,T,Y_LT5,UKJ3",111115,112400,113994,114878,115088,114838,113832,111716,109020,106460,...,104900,106300,107900,109400,110800,111600,112300,112800,:,:
"NR,T,Y_LT5,UKJ4",109502,110231,110456,110190,109673,108970,107597,105719,103498,101228,...,97500,98000,99000,100300,101400,102000,102400,102700,:,:
"NR,T,Y_LT5,UKK",300647,303488,306802,307419,306427,304334,300332,294269,288007,281796,...,276800,278700,280400,283300,287500,289300,291300,292100,:,:
"NR,T,Y_LT5,UKK1",144767,145670,146928,147148,146817,146003,144252,141249,137989,134775,...,131000,131500,131800,132800,134300,135000,135700,135600,:,:
"NR,T,Y_LT5,UKK2",67022,67838,68648,68784,68693,68506,67776,66406,65001,63553,...,62900,63800,64100,64600,65600,65900,66200,66200,:,:
"NR,T,Y_LT5,UKK3",28728,29154,29516,29446,29123,28654,28015,27394,26797,26202,...,26000,26100,26300,26600,27100,27600,28000,28500,:,:
"NR,T,Y_LT5,UKK4",60130,60826,61710,62041,61794,61171,60289,59220,58220,57266,...,56700,57500,58400,59400,60300,60900,61400,61800,:,:
"NR,T,Y_LT5,UKL",170455,171985,174596,176798,178222,179299,179136,176992,174039,170933,...,173500,176000,178400,181800,185600,188000,189900,191400,:,:
"NR,T,Y_LT5,UKL1",104715,105813,107564,108847,109634,110182,110065,109071,107776,106286,...,108600,110600,112500,114700,117500,119300,120500,121600,:,:
"NR,T,Y_LT5,UKL2",65740,66172,67032,67951,68588,69117,69071,67921,66263,64647,...,64700,65200,65900,67000,68100,68900,69500,69800,:,:
"NR,T,Y_LT5,UKM",281519,284670,289213,291514,292947,294887,294663,292223,289177,284774,...,294797,303742,306664,317634,322857,324467,325476,325733,:,:
"NR,T,Y_LT5,UKM2",:,110374,111787 e,112608 e,113183,113988,113797,112641,111182,109158,...,112152,113746,115987,117957,120628,120907,120684,:,:,:
"NR,T,Y_LT5,UKM3",:,124782,126487 e,127875 e,128437,129188,129196,128569,128072,127041,...,136505,139970,142229,145918,149453,151472,152118,:,:,:
"NR,T,Y_LT5,UKM5",26842,26930,27316,27583,27665,27548,27123,26503,25820,25005,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKM6",22346,22567,23003,23280,23653,24163,24547,24510,24103,23570,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKM7",103060,104236,106046,106898,107401,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKM8",82281,83238,84328,84807,84929,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKM9",46990,47699,48520,48946,49299,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
"NR,T,Y_LT5,UKN",122438,123882,125040,125548,126232,127000,126711,124844,122276,119405,...,120391,122122,122607,125608,127283,129013,130033,130444,:,:
"NR,T,Y_LT5,UKN0",122438,123882,125040,125548,126232,127000,126711,124844,122276,119405,...,120391,122122,122607,125608,127283,129013,130033,130444,:,:

In [59]:
indices = []
for val in data.index:
    split = val.split(',')
    indices.append(len(split[-1]) == 2 and split[-2] == "TOTAL" and split[-3] == 'T')

In [66]:
data = data[indices]

In [67]:
two_letter_to_country_name = \
{
    "AL": "Albania",
    "AT": "Austria",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "CH": "Switzerland",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DK": "Denmark",
    "EE": "Estonia",
    "EL": "Greece",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "HR": "Croatia",
    "HU": "Hungary",
    "IE": "Ireland",
    "IS": "Iceland",
    "IT": "Italy",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "ME": "Montenegro",
    "MK": "North Macedonia",
    "MT": "Malta",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RS": "Serbia",
    "SE": "Sweden",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "TR": "Turkey",
    "UK": "United Kingdom"
    
}

In [68]:
data.index = pd.Index(list(map(lambda x: two_letter_to_country_name[x.split(',')[-1]], data.index)))
data

,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
Albania,2870324,2876591,2875592,2885796,2892394,2897770,2903008,2907361,2918674,2936355,...,:,:,:,:,:,:,:,:,:,:
Austria,8822267,8772865,8700471,8584926,8507786,8451860,8408121,8375164,8351643,8335003,...,7982461,7971116,7964966,7953067,7943489,7928746,7882519,7798899,7710882,7644818
Belgium,11398589,11351727,11311117,11237274,11180840 b,11137974,11075889 b,11000638 b,10839905,10753080,...,10213752,10192264,10170226,10143047,10130574,10100631,10068319,10021997,9986975,9947782
Bulgaria,7050034,7101859,7153784,7202198,7245677,7284552,7327224,7369431,7421766,7467119,...,8230371,8283200,8340936,8384715,8427418,8459763,8484863,8595465,8669269,8767308
Switzerland,8484130,8419550,8327126,8237666,8139631,8039060,7954662,7870134 b,7785806,7701856,...,7123537,7096465,7081346,7062354,7019019,6968570,6907959,6842768,6757188,6673850
Cyprus,864236,854802,848319,847008,858000,865878,862011,839751,819140 b,796930,...,682862,675215,666313,656333,645399,632944,619231,603069,587141,572655
Czech Republic,10610055,10578820,10553843,10538275,10512419,10516125,10505445,10486731,10462088,10425783,...,10289621,10299125,10309137,10321344,10333161,10334013,10325697,10312548,10304607,10362102
Germany,82792351,82521653,82175684,81197537,80767463,80523746,80327900,80222065 b,81802257,82002356,...,82037011,82057379,82012162,81817499,81538603,81338093,80974632,80274564,79753227,79112831
Denmark,5781190,5748769,5707251,5659715,5627235,5602628,5580516,5560628,5534738,5511451,...,5313577,5294860,5275121,5251027,5215718,5196642,5180614,5162126,5146469,5135409
Estonia,1319133,1315635,1315944,1314870 b,1315819,1320174,1325217,1329660,1333290,1335740,...,1379237,1393074,1405996,1425192,1448075,1476952,1511303,1554878,1567749,1570599
Greece,10741165,10768193,10783748,10858018,10926807,11003615,11086406,11123392,11119289,11094745,...,10747768,10693250,10629267,10588332,10535973,10489871,10430958,10367163,10272691,10120892
Spain,46658447,46528024,46440099,46449565,46512199,46727890,46818219,46667174,46486619,46239273,...,40303568,40143449,39971329,39808374,39639726,39458489,39264034,39051336,38881416,38853227
Finland,5513130,5503297,5487308,5471753,5451270,5426674.0,5401267.0,5375276.0,5351427.0,5326314.0,...,5159646.0,5147349.0,5132320.0,5116826.0,5098754.0,5077912.0,5054982.0,5029002.0,4998478.0,4974383.0
France,66926166,66804121,66638391,66458153,66165980,65600350,65276983 p,64978721,64658856,64350226,...,60158533,58298962,58116018,57935959,57752535,57565008,57369161,57110533,56840661,56577000
Croatia,4105493,4154213,4190669,4225316,4246809,4262140,4275984,4289857,4302847,4309796,...,4527459,4536812,4533028,4581167,4658893,4645155,4555771,4595866,4782179,4772556
Hungary,9778371,9797561,9830485,9855571,9877365,9908798,9931925 b,9985722,10014324,10030975,...,10253416,10279724,10301247,10321229,10336700,10350010,10365035,10373647,10373153,10374823
Ireland,4830392,4784383,4726286,4677627,4637852,4609779,4589287,4570881,4549428,4521322,...,3732006,3693386,3654955,3620065,3597617,3583154,3569367,3547492,3520977,3506970
Iceland,348450,338349,332529,329100,325671,321857,319575,318452,317630,319368,...,275712,272381,269874,267958,266978,265064,262386,259727,255866,253785
Italy,60483973,60589445,60665551,60795612,60782668,59685227,59394207,59364690,59190143,59000586,...,56909109,56904379,56876364,56844197,56844408,56842392,56821250,56772923,56744119,56694360
Liechtenstein,38114,37810,37622,37366,37129,36838,36475,36149,35894,35589,...,32015,31320,31143,30923,30629,30310,29868,29386,29032,28452
Lithuania,2808901,2847904,2888558,2921262,2943472,2971905,3003641,3052588,3141976,3183856,...,3536401,3562261,3588013,3615212,3642991,3671296,3693929,3706299,3701968,3693708
Luxembourg,602005,590667 b,576249,562958,549680,537039,524853,511840,502066,493500,...,427350,422050,416850,411600,405650,400200,394750,389600,384400,379300
Latvia,1934379,1950116,1968957,1986096,2001468,2023825,2044813,2074605,2120504,2162834,...,2399248,2420789,2444912,2469531,2500580,2540904,2585675,2643000,2658161,2668140
Montenegro,622359,622387,622218,622099,621521,620893,620308,619850,619001,617157,...,:,:,:,:,:,:,:,:,:,:
North Macedonia,2075301,2073702,2071278,2069172,2065769,2062294,2059794 p,2057284,2052722,2048619,...,2012705,2002340,1991398,1971687,1957265,1936741,2061000,1908941,1890872,1873109
Malta,475701,460297,450415,439691,429424,422509,417546,414989,414027,410926,...,378518,376513,373958,371415,369451,366431,362977,359543,355910,352430
Netherlands,17181084,17081507,16979120,16900726,16829289,16779575,16730348,16655799,16574989,16485787,...,15760225,15654192,15567107,15493889,15424122,15341553,15239182,15129150,15010445,14892574
Norway,5295619,5258317,5210721,5166493,5107970,5051275,4985870,4920305,4858199,4799252,...,4445329,4417599,4392714,4369957,4348410,4324815,4299167,4273634,4249830,4233116
Poland,37976687,37972964,37967209,38005614,38017856,38062535,38063792,38062718,38022869 b,38135876,...,38666983,38659979,38639341,38609399,38580597,38504707,38418108,38309226,38183160,38038403
Portugal,10291027,10309573,10341330 e,10374822 e,10427301,10487289,10542398,10572721,10573479,10563014,...,10186634,10133758,10084196,10043693,10008659,9974391,9954958,9950029,9970441,9995995
Romania,19530631,19644350,19760585,19870647 e,19947311 e,20020074,20095996 b,20199059,20294683,20440290,...,22488595,22526093,22581862,22656145,22712394,22748027,22778533,22810035,23192274,23211395
Serbia,7001444,7040272,7076372,7114393,7146759,7181505,7216649,7251549 b,7306677,7334937,...,7552850,:,:,:,:,:,:,:,:,:
Sweden,10120242,9995153,9851017,9747355,9644864,9555893,9482855,9415570,9340682,9256347,...,8854322,8847625,8844499,8837496,8816381,8745109,8692013,8644120,8590630,8527039
Slovenia,2066880,2065895,2064188,2062874,2061085,2058821,2055496,2050189,2046976,2032362,...,1978334,1984923,1986989,1990266,1989477,1989408,1994084,1998912,1999945,1996377
Slovakia,5443120,5435343,5426252,5421349,5415949,5410836,5404322,5392446,5390410,5382401,...,5393382,5387650,5378932,5367790,5356207,5336455,5314155,5295877,5310711,5287663
Turkey,80810525,79814871,78741053,77695904,76667864,75627384,74724269,73722988,72561312,71517100,...,65786563,64641675,63484661,62337617,61203584,60079060,58958565,57835076,56714051,55494711
United Kingdom,66273576,65844142,65379044,64853393,64351203,63905297,63495303,63022532,62510197,62042343,...,58579685,58394596,58239312,58094587,57943472,57788017,57649210,57511594,57338199,57156972